### ISSUE TITLE
l3backend-xdvipdfmx.def' not found. 

### ISSUE THREAD

**Issue by zhengdechang** [adamkaplan0/latextableviewer#25]
![image](https://github.com/adamkaplan0/latextableviewer/assets/77528948/a8977f88-b0c6-4fb0-ae28-3b8fc128472a)

Compiler Log:

This is XeTeX, Version 3.14159265-2.6-0.999992 (XeTeX WebAssembly 0.3.0) (preloaded format=swiftlatexxetex) entering extended mode (main.tex LaTeX2e <2020-02-02> patch level 2 L3 programming layer <2020-02-14> (/tex/article.cls Document Class: article 2020/04/10 v1.4m Standard LaTeX document class (/tex/size10.clo)) (/tex/mathtools.sty (/tex/keyval.sty) (/tex/calc.sty) (/tex/mhsetup.sty) (/tex/amsmath.sty For additional information on amsmath, use the `?' option. (/tex/amstext.sty (/tex/amsgen.sty)) (/tex/amsbsy.sty) (/tex/amsopn.sty))) (/tex/amssymb.sty (/tex/amsfonts.sty)) (/tex/booktabs.sty) ! LaTeX Error: File `l3backend-xdvipdfmx.def' not found. Type X to quit or <RETURN> to proceed, or enter new name. (Default extension: def) Enter file name: ! Emergency stop. <read *> l.5 \begin{document} ^^M No pages of output. Transcript written on main.log.

WCan you help me tell me what caused this

**Comment by zhengdechang** [comment]
![image](https://github.com/adamkaplan0/latextableviewer/assets/77528948/29c19e70-95c9-4ba9-b9cc-63d8c79fe7c7)
301

**Comment by adamkaplan0** [comment]
Hey!

Would you be able to share your LaTeX input code with me or at least any additional packages you are importing? There is a chance that you are importing a package not included in the current version of `texlive-full` installed on the backend and I can look into adding it.

**Comment by devixyz** [comment]
I used the DockerFile you provided to solve it，but using python to start the service after a linux installation will not work

**Comment by adamkaplan0** [comment]
Since there has been no action on this and I cannot replicate the issue, I'm marking this as stale.
